name = "ipinfo"
main = "src/worker.ts"
compatibility_date = "2023-06-11"
usage_model = "bundled"
env = { }

[[routes]]
pattern = "gusdleon.com/api/ipv4info*"
zone_name = "gusdleon.com"

[[routes]]
pattern = "gusdleon.com/api/ipv6info*"
zone_name = "gusdleon.com"

[triggers]
crons = [ ]
