name = "ipinfo"
main = "src/worker.ts"
compatibility_date = "2023-06-11"
workers_dev = false
env = { }

[[routes]]
pattern = "gusdleon.com/api/ipv4info*"
zone_name = "gusdleon.com"

[[routes]]
pattern = "gusdleon.com/api/ipv6info*"
zone_name = "gusdleon.com"

[placement]
mode = "smart"

[observability]
enabled = true
head_sampling_rate = 1

[triggers]
crons = [ ]
